[project]
name = "cp-contest"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy>=2.2.0",
    "pytest>=8.3.4",
    "scipy>=1.14.1",
]
